app_user:
  type: rest
  resource: AppBundle\Controller\UserController
  name_prefix: api_

app_homepage:
  type: annotation
  resource: AppBundle\Controller\DefaultController

app_api_login:
  type: annotation
  resource: AppBundle\Controller\SecurityController